# Pizza API

## To use these HTTP endpoint install the REST Client plugin in VSCode.

### Get all the Pizzas from the API

GET https://pizza-api.projectcodex.net/api/pizzas

### Create a cart

GET https://pizza-api.projectcodex.net/api/pizza-cart/create?username=lelly-99


### Get a cart

GET https://pizza-api.projectcodex.net/api/pizza-cart/SnL6UPNEEo/get

### Add a pizza to the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/add
content-type: application/json

{
	"cart_code" : "SnL6UPNEEo",
	"pizza_id" : 6
}


### Remove a pizza from the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/remove
content-type: application/json

{
	"cart_code" : "SnL6UPNEEo",
	"pizza_id" : 5
}

### GET all the carts for a given user

GET https://pizza-api.projectcodex.net/api/pizza-cart/username/

### GET all the active carts for a user

GET https://pizza-api.projectcodex.net/api/pizza-cart/username/lelly-99/active


### Pay for a pizza from the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/pay	
content-type: application/json

{
	"cart_code" : "2da8TDNKSy",
	"amount" : 400
}

